### PR TITLE
Code now parallelized.

### PR DESCRIPTION
**Pull request by jayanthjaiswal**

### CODE REVIEW

**Comment by jayanthjaiswal** [comment]
Basically, you can run it on a computer with say 16 cores and the code will then run almost 16 times faster now (not taking process creation and context switch overhead into account) :slightly_smiling_face:
It will spawn one process for each CPU core on your machine. Each CPU core can execute one process  which checks ATF file simultaneously.

Will fix the Xcode build in seperate commit.

**Comment by raquel-ucl** [comment]
Hi @jayanthjaiswal. Thanks for this PR! You closed it without merging, is that what you intended?

**Comment by jayanthjaiswal** [comment]
@raquel-ucl, I will create another seperate clean pull request after more testing and with build fix.

**Comment by raquel-ucl** [comment]
Ok, thanks!

**Pull request closed without merging**
